In [1]:
import pandas as pd

df = pd.read_csv("CP_count_PUMA.csv")
df

,smiles,1_1,10_19,10_20,100_277,100_278,104_291,105_355,105_369,105_361,...,Cells_Neighbors_FirstClosestObjectNumber_Adjacent,Cells_Neighbors_SecondClosestObjectNumber_5,Cells_Neighbors_SecondClosestObjectNumber_Adjacent,Cells_Parent_Nuclei,Cytoplasm_Number_Object_Number,Cytoplasm_Parent_Cells,Cytoplasm_Parent_Nuclei,Nuclei_Neighbors_FirstClosestObjectNumber_1,Nuclei_Neighbors_SecondClosestObjectNumber_1,Nuclei_Number_Object_Number
0,CCOC(=O)c1ccc(NC(=S)N2CCSC2c2ccc(OC)cc2)cc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.765625,0.890625,0.890625,1.328125,1.328125,1.328125,1.328125,0.960938,1.320312,1.328125
1,O=C(CC1NC(=O)NC1=O)Nc1cccc2ccccc12,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.078125,2.718750,2.718750,2.503906,2.503906,2.503906,2.503906,3.242188,2.578125,2.503906
2,CC(Nc1nc(nc2ccccc12)N1CCCC1)c1ccccc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-7.765625,-8.140625,-8.140625,-8.250000,-8.250000,-8.250000,-8.250000,-7.710938,-7.546875,-8.250000
3,CCCC(Oc1ccc(Br)cc1)c1nc2c3cc(OC)c(OC)cc3nc(S)n2n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-7.320312,-7.828125,-7.828125,-7.796875,-7.804688,-7.796875,-7.796875,-7.859375,-7.695312,-7.804688
4,CC1=C(C(NC(=O)N1)c1ccc(F)cc1)C(=O)OCc1ccc2OCOc2c1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-10.953125,-10.390625,-10.390625,-10.960938,-10.960938,-10.960938,-10.960938,-11.406250,-10.781250,-10.960938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16165,COC(=O)[C@H]1[C@H](CO)[C@H]2Cn3c(=O)c(\C=C\C)c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.039062,-2.031250,-2.031250,-1.550781,-1.550781,-1.550781,-1.550781,-1.546875,-2.945312,-1.550781
16166,C\C=C\c1ccc2n(C[C@H]3[C@H](CO)[C@H](N(C)[C@@H]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.851562,-0.359375,-0.359375,-0.835938,-0.835938,-0.835938,-0.835938,-1.328125,-0.804688,-0.835938
16167,C\C=C\c1ccc2n(C[C@@H]3[C@@H](CO)[C@@H](N(C)[C@...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.851562,-3.359375,-3.359375,-3.835938,-3.835938,-3.835938,-3.835938,-3.328125,-4.054688,-3.835938
16168,C\C=C\c1ccc2n(C[C@H]3[C@H](CO)[C@@H](C(=O)N[C@...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.039062,-2.460938,-2.460938,-3.300781,-3.300781,-3.300781,-3.300781,-3.382812,-2.937500,-3.300781
16169,COC(=O)[C@@H]1[C@@H](CO)[C@@H]2Cn3c(=O)c(\C=C\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.210938,-3.312500,-3.312500,-3.308594,-3.308594,-3.308594,-3.308594,-3.804688,-2.789062,-3.308594

In [2]:
df.iloc[:, :271]

,smiles,1_1,10_19,10_20,100_277,100_278,104_291,105_355,105_369,105_361,...,88_252,88_254,89_255,9_14,9_17,9_18,90_256,91_257,92_258,93_259
0,CCOC(=O)c1ccc(NC(=S)N2CCSC2c2ccc(OC)cc2)cc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,O=C(CC1NC(=O)NC1=O)Nc1cccc2ccccc12,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CC(Nc1nc(nc2ccccc12)N1CCCC1)c1ccccc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CCCC(Oc1ccc(Br)cc1)c1nc2c3cc(OC)c(OC)cc3nc(S)n2n1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CC1=C(C(NC(=O)N1)c1ccc(F)cc1)C(=O)OCc1ccc2OCOc2c1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16165,COC(=O)[C@H]1[C@H](CO)[C@H]2Cn3c(=O)c(\C=C\C)c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16166,C\C=C\c1ccc2n(C[C@H]3[C@H](CO)[C@H](N(C)[C@@H]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16167,C\C=C\c1ccc2n(C[C@@H]3[C@@H](CO)[C@@H](N(C)[C@...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16168,C\C=C\c1ccc2n(C[C@H]3[C@H](CO)[C@@H](C(=O)N[C@...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16169,COC(=O)[C@@H]1[C@@H](CO)[C@@H]2Cn3c(=O)c(\C=C\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
assays_list = df.columns.to_list()[1:-13]
len(assays_list)

270

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingClassifier


def load_and_preprocess_testdata(fold):
    test_path = f"PUMA/predictions/chemical_cv{fold}/assay_matrix_discrete_test_scaff.csv"

    
    test_data = pd.read_csv(test_path)[["smiles"]]
    test_data = pd.merge(test_data, df, on="smiles")
    
    return test_data

In [10]:
import numpy as np
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

from sklearn.utils import class_weight
from sklearn.model_selection import GridSearchCV

# Initialize a list to store AUC scores for all folds
all_auc_scores = []

# Initialize an empty list to hold models for each fold
models_per_fold = []

# Define the fold indices (adjust based on your data split)
folds = ["0", "1", "2", "3", "4"]

# Predict for each individual fold using the corresponding model
for i in tqdm(range(0,25)):
    for idx, fold in enumerate(folds):
        # Load and preprocess data for the current test fold
        test_data = load_and_preprocess_testdata(fold)

        # Loop through each assay in the test set for the current fold
        for assay in (assays_list):
            test_data_assay = test_data[~test_data[assay].isna()][[assay, "Cells_Number_Object_Number"]]

            # Separate features and target variable
            y_test = test_data_assay[assay].astype(int)

            if len(y_test) == 0:
                print(f"Skipping assay {assay} in fold {fold} due to no test data")
                continue

            # Make predictions using the model for the current fold
            y_pred = np.random.permutation(y_test)

            # Calculate AUC score
            auc_score = np.nan    
            try:
                auc_score = roc_auc_score(y_test, y_pred)
            except:
                continue

            # Store the AUC score along with fold and assay information
            all_auc_scores.append({"Fold": fold, "Task": assay, "AUC": auc_score})

# Convert the AUC results to a DataFrame for convenience
auc_df = pd.DataFrame(all_auc_scores)

# Save the DataFrame to a CSV file
auc_df.to_csv("auc_scores_yscrambling.csv", index=False)

# Display the AUC DataFrame
auc_df

100%|██████████| 25/25 [01:23<00:00,  3.33s/it]

      Fold     Task       AUC
0        0      1_1  0.476190
1        0  100_277  0.437500
2        0  100_278  0.678571
3        0  104_291  0.384615
4        0  105_369  0.466667
...    ...      ...       ...
25270    4     9_18  0.300000
25271    4   90_256  0.482143
25272    4   91_257  0.375000
25273    4   92_258  0.375000
25274    4   93_259  0.350000

[25275 rows x 3 columns]

In [15]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# Assuming df is your DataFrame and is already defined
num_iterations = 1  # Number of repetitions
thresholds = [0.5, 0.6, 0.7, 0.8, 0.9, 0.999]  # AUC thresholds


# Calculate mean AUC for each target across all iterations
mean_auc = auc_df[["Task", "AUC"]].groupby("Task").mean()

# Count the number of targets with AUC > 0.5, 0.7, 0.8, and 0.9
count_above_thresholds = {
    threshold: (mean_auc > threshold).sum() for threshold in thresholds
}

# Display results
print("Mean AUC for each target:")
print("\nNumber of targets with AUC > thresholds:")
print(count_above_thresholds)

Mean AUC for each target:

Number of targets with AUC > thresholds:
{0.5: AUC    134
dtype: int64, 0.6: AUC    4
dtype: int64, 0.7: AUC    0
dtype: int64, 0.8: AUC    0
dtype: int64, 0.9: AUC    0
dtype: int64, 0.999: AUC    0
dtype: int64}

In [16]:
mean_auc

              AUC
Task
100_277  0.507067
100_278  0.495952
104_289  0.525974
104_291  0.513077
104_295  0.497143
...           ...
92_258   0.524286
93_259   0.502872
9_14     0.610000
9_17     0.520000
9_18     0.527333

[269 rows x 1 columns]

In [17]:
mean_auc.mean()

AUC    0.502412
dtype: float64

In [18]:
mean_auc.std()

AUC    0.025072
dtype: float64